-- 0001_append_only_triggers.sql
-- Authored for fartola. Hand-authored, not generated by drizzle-kit.
-- Enforces REQ-EVT-002 (events table append-only). See ADR-0003.
-- Co-versioned with 0000_initial.sql; drizzle-kit never regenerates this file
-- because drizzle-kit only writes the next-numbered migration when schema diffs,
-- and there is no schema-as-TS trigger primitive. Future `db:generate` runs
-- regenerate 0000_initial.sql (which has no triggers — that is correct) and
-- leave this 0001 file alone. The meta/_journal.json entry for this migration
-- must be re-appended whenever drizzle-kit rewrites the journal during a 0000
-- regeneration (locked by codex review C-H1).

CREATE TRIGGER IF NOT EXISTS events_no_update BEFORE UPDATE ON events
  BEGIN SELECT RAISE(ABORT, 'events table is append-only'); END;
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS events_no_delete BEFORE DELETE ON events
  BEGIN SELECT RAISE(ABORT, 'events table is append-only'); END;
