-- 0004_eventor_fts.sql
-- Authored for fartol. Hand-authored, not generated by drizzle-kit
-- (drizzle-kit has no schema-as-TS primitive for FTS5 virtual tables).
--
-- Adds two FTS5 mirror tables backing the smart name + club picker:
--   eventor_competitors_fts(rowid=person_id, family_name, given_name, club_name)
--   eventor_clubs_fts(rowid=club_id, name, short_name, media_name)
--
-- Tokenizer: unicode61 remove_diacritics 2 — folds å→a, ö→o, ñ→n so an
-- operator searching for "marsell" finds "Mårsell". Mode 2 is the
-- recommended setting; mode 0 keeps diacritics, mode 1 had a bug fixed
-- in 2018 (covered all Latin-1 only).
--
-- Why a mirror table (not external content):
--   The competitor cache is wipe-and-reload — ingestEventorCache DELETEs
--   all rows then bulk-INSERTs in a single transaction. An external-content
--   FTS5 would need synchronous DELETE/INSERT trigger calls that the
--   external-content semantics make brittle around bulk transactions.
--   A standalone mirror with AFTER INSERT / AFTER DELETE triggers does the
--   same job, costs ~30 MB extra for 252k rows (acceptable; the
--   competitor cache itself is ~90 MB uncompressed), and keeps the
--   ingest path agnostic of the FTS layer.
--
-- club_name in eventor_competitors_fts comes from a JOIN to eventor_clubs
-- on INSERT. The ingest order (clubs first, then competitors) guarantees
-- the JOIN target exists when the competitor row is inserted.

CREATE VIRTUAL TABLE IF NOT EXISTS eventor_competitors_fts USING fts5(
  family_name,
  given_name,
  club_name,
  tokenize = 'unicode61 remove_diacritics 2'
);--> statement-breakpoint

CREATE VIRTUAL TABLE IF NOT EXISTS eventor_clubs_fts USING fts5(
  name,
  short_name,
  media_name,
  tokenize = 'unicode61 remove_diacritics 2'
);--> statement-breakpoint

-- Trigger: keep eventor_competitors_fts in sync.
-- The JOIN lifts club_name in at INSERT time so the FTS row is denormalised
-- and the search can match across all three columns in a single MATCH query.
CREATE TRIGGER IF NOT EXISTS eventor_competitors_ai AFTER INSERT ON eventor_competitors
BEGIN
  INSERT INTO eventor_competitors_fts(rowid, family_name, given_name, club_name)
    SELECT
      NEW.person_id,
      NEW.family_name,
      NEW.given_name,
      COALESCE((SELECT name FROM eventor_clubs WHERE club_id = NEW.club_id), '');
END;--> statement-breakpoint

CREATE TRIGGER IF NOT EXISTS eventor_competitors_ad AFTER DELETE ON eventor_competitors
BEGIN
  DELETE FROM eventor_competitors_fts WHERE rowid = OLD.person_id;
END;--> statement-breakpoint

-- Trigger: keep eventor_clubs_fts in sync.
CREATE TRIGGER IF NOT EXISTS eventor_clubs_ai AFTER INSERT ON eventor_clubs
BEGIN
  INSERT INTO eventor_clubs_fts(rowid, name, short_name, media_name)
    VALUES (NEW.club_id, NEW.name, COALESCE(NEW.short_name, ''), COALESCE(NEW.media_name, ''));
END;--> statement-breakpoint

CREATE TRIGGER IF NOT EXISTS eventor_clubs_ad AFTER DELETE ON eventor_clubs
BEGIN
  DELETE FROM eventor_clubs_fts WHERE rowid = OLD.club_id;
END;--> statement-breakpoint

-- Initial population: backfill from any existing cache rows so the
-- migration is idempotent on a populated DB (operator already ran a
-- full Eventor refresh before upgrading).
INSERT INTO eventor_clubs_fts(rowid, name, short_name, media_name)
  SELECT club_id, name, COALESCE(short_name, ''), COALESCE(media_name, '')
  FROM eventor_clubs
  WHERE NOT EXISTS (
    SELECT 1 FROM eventor_clubs_fts WHERE eventor_clubs_fts.rowid = eventor_clubs.club_id
  );--> statement-breakpoint

INSERT INTO eventor_competitors_fts(rowid, family_name, given_name, club_name)
  SELECT
    c.person_id,
    c.family_name,
    c.given_name,
    COALESCE(k.name, '')
  FROM eventor_competitors c
  LEFT JOIN eventor_clubs k ON k.club_id = c.club_id
  WHERE NOT EXISTS (
    SELECT 1 FROM eventor_competitors_fts WHERE eventor_competitors_fts.rowid = c.person_id
  );
