-- 0006_eventor_fts_update_triggers.sql
-- Authored for fartola. Hand-authored, not generated by drizzle-kit
-- (drizzle-kit has no schema-as-TS primitive for FTS5 triggers).
--
-- Defense-in-depth follow-up to 0004_eventor_fts.sql: that migration
-- created AFTER INSERT and AFTER DELETE triggers but no AFTER UPDATE.
-- The current ingest path is wipe-and-reload (DELETE-all + INSERT-all
-- inside a single transaction) so the missing UPDATE trigger is not
-- exploitable today. If a future incremental-refresh path ever issues
-- UPDATE on eventor_competitors / eventor_clubs, the FTS index would
-- silently go stale without this trigger.
--
-- club_name on the competitor row is denormalised — the trigger re-
-- resolves it from eventor_clubs at UPDATE time so a club rename
-- propagates to the FTS mirror.

CREATE TRIGGER IF NOT EXISTS eventor_competitors_au AFTER UPDATE ON eventor_competitors
BEGIN
  DELETE FROM eventor_competitors_fts WHERE rowid = OLD.person_id;
  INSERT INTO eventor_competitors_fts(rowid, family_name, given_name, club_name)
    SELECT
      NEW.person_id,
      NEW.family_name,
      NEW.given_name,
      COALESCE((SELECT name FROM eventor_clubs WHERE club_id = NEW.club_id), '');
END;--> statement-breakpoint

CREATE TRIGGER IF NOT EXISTS eventor_clubs_au AFTER UPDATE ON eventor_clubs
BEGIN
  DELETE FROM eventor_clubs_fts WHERE rowid = OLD.club_id;
  INSERT INTO eventor_clubs_fts(rowid, name, short_name, media_name)
    VALUES (NEW.club_id, NEW.name, COALESCE(NEW.short_name, ''), COALESCE(NEW.media_name, ''));
END;
