// Authored for fartol. Not ported from upstream.
//
// Drizzle schema-as-TS for the Phase 1 single-laptop training MVP. Defines
// the events table (immutable, append-only) plus seven mutable config
// tables (competitions, classes, controls, courses, course_controls,
// competitors, clubs) and one internal singleton config table (config)
// for storing the node_id across restarts.
//
// Locked by:
// - .planning/adr/0003-event-sourcing-as-core-data-model.md (events table
//   is immutable — enforced by triggers in 0001_append_only_triggers.sql)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-09
//   (mutable config tables — Phase 1 uses CRUD; Phase 2 will layer Yjs
//   on top of these tables for multi-operator editing)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-10
//   (Drizzle ORM on better-sqlite3, schema-as-TS, built-in migrations)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-11
//   (card-to-competitor matching = hybrid; partial unique index on
//   competitors.(competition_id, card_number) where card_number IS NOT NULL)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-12
//   (DNF/MP is a pure projection over the event log — no precomputed
//   status column on competitors)
// - .planning/phases/01-single-laptop-training-mvp/01-CONTEXT.md D-15
//   (wizard fields: name + date + receipt_template + auto_print)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-H1
//   (append-only triggers live in a SEPARATE migration file
//   0001_append_only_triggers.sql — drizzle-kit's schema-as-TS has no
//   trigger primitive, so the planner-original scheme of appending the
//   trigger SQL to 0000_initial.sql was fragile: future `db:generate`
//   regenerates 0000 and erases the triggers. The 0001 file is never
//   regenerated by drizzle-kit, so it survives every `db:generate` run)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-H5
//   (shared-types is a pure DTO package. Drizzle row inference lives in
//   apps/edge/src/db/types.ts — NOT in packages/shared-types. This file
//   has zero downward dependencies on shared-types and the EventPayload
//   union is defined locally so the schema stays self-contained)
// - .planning/phases/01-single-laptop-training-mvp/01-REVIEWS.md §C-M4
//   (competitors.consent_status TEXT NOT NULL DEFAULT 'explicit'; values
//   are 'explicit' (walk-up checkbox), 'pending_first_read' (EntryList
//   import — operator confirms on first card_read), 'confirmed_on_read'
//   (after one-time confirmation toast). Plan 05 sets 'pending_first_read';
//   plan 14 surfaces the toast that flips to 'confirmed_on_read')
// - .planning/research/architecture.md §"Event log schema"
//   (columns: node_id, local_seq, competition_id, event_type,
//   event_time_ms, recorded_at_ms, payload; PRIMARY KEY (node_id,
//   local_seq); indexes on event_time_ms, competition_id, and
//   (competition_id, event_type))
//
// REQ-EVT-001..004 (event log shape + immutability)
// REQ-EVT-CMP-001 (competitor/class/course config)
// REQ-PRIV-001 (consent_at_ms on competitor row)
// REQ-PRIV-002 (scrubbable PII columns — name + club nulled by plan 17)

import { sql } from 'drizzle-orm';
import {
  sqliteTable,
  text,
  integer,
  primaryKey,
  index,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import type { NdjsonPunch, HalfDayClock } from '@fartol/sportident';

// ---------------------------------------------------------------------------
// EventPayload — discriminated union stored as JSON in events.payload.
//
// The `card_read` arm mirrors Phase 0's CardReadEvent shape exactly (codex
// C-H2 — plan 06 wires the bridge that produces these payloads; locking the
// type at the schema layer means a wrong-shape insert is a compile error).
//
// Phase 1 adds five non-Phase-0 event types that flow only through
// apps/edge — they never travel over the NDJSON wire from packages/sportident.
// All keys snake_case at the JSON boundary per PATTERNS S-6.
// ---------------------------------------------------------------------------

export type EventPayload =
  | {
      event_type: 'card_inserted';
      card_number: number;
      card_type: string;
    }
  | {
      event_type: 'card_read';
      card_number: number;
      card_type: string;
      start: HalfDayClock | null;
      finish: HalfDayClock | null;
      check: HalfDayClock | null;
      clear: HalfDayClock | null;
      punch_count: number;
      punches: NdjsonPunch[];
      card_holder: Record<string, unknown> | null;
      card_series_byte?: number;
      uid?: number;
    }
  | {
      event_type: 'card_removed';
      card_number: number;
    }
  | {
      event_type: 'card_bound';
      competitor_id: string;
      card_number: number;
      walkup: boolean;
      consent_at_ms: number;
    }
  | {
      event_type: 'manual_dnf';
      competitor_id: string;
      reason: string;
    }
  | {
      event_type: 'un_dnf';
      competitor_id: string;
    }
  | {
      event_type: 'frame_error';
      reason: string;
      raw: string;
    }
  | {
      event_type: 'connection_changed';
      state: 'opening' | 'open' | 'error' | 'closed';
      error?: string;
    }
  | {
      event_type: 'consent_confirmed';
      competitor_id: string;
      prior_consent_status: 'pending_first_read';
    };

// ---------------------------------------------------------------------------
// competitions — mutable. D-09 (config tables are CRUD; punches are events).
// D-15 (wizard) locks the four mutable fields. UI-SPEC §Auto-print toggle
// defaults auto_print to 0 (OFF); UI-SPEC §"Receipt template DEFAULT" pins
// receipt_template to 'classic' on create.
// ---------------------------------------------------------------------------

export const competitions = sqliteTable('competitions', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  /** ISO date 'YYYY-MM-DD' — UI-SPEC §Visual Anchors. */
  date: text('date').notNull(),
  receiptTemplate: text('receipt_template').notNull().default('classic'),
  autoPrint: integer('auto_print', { mode: 'boolean' }).notNull().default(false),
  createdAtMs: integer('created_at_ms').notNull(),
});

// ---------------------------------------------------------------------------
// classes — mutable. Cascade-deletes when the parent competition is deleted
// (which only happens in dev / test fixture setup; production never deletes
// a real competition).
// ---------------------------------------------------------------------------

export const classes = sqliteTable(
  'classes',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    shortName: text('short_name'),
  },
  (t) => [uniqueIndex('classes_name_per_comp').on(t.competitionId, t.name)]
);

// ---------------------------------------------------------------------------
// controls — mutable. Code is the SportIdent control code (typically 31-150).
// ---------------------------------------------------------------------------

export const controls = sqliteTable(
  'controls',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    code: integer('code').notNull(),
  },
  (t) => [uniqueIndex('controls_code_per_comp').on(t.competitionId, t.code)]
);

// ---------------------------------------------------------------------------
// courses — mutable. A course typically maps 1:1 to a class but XML import
// may assign later (D-03), so class_id is NULL-able.
// ---------------------------------------------------------------------------

export const courses = sqliteTable('courses', {
  id: text('id').primaryKey(),
  competitionId: text('competition_id')
    .notNull()
    .references(() => competitions.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  classId: text('class_id').references(() => classes.id),
  lengthM: integer('length_m'),
  climbM: integer('climb_m'),
});

// ---------------------------------------------------------------------------
// course_controls — mutable. Ordered list of controls per course. order_idx
// is 0-based.
// ---------------------------------------------------------------------------

export const courseControls = sqliteTable(
  'course_controls',
  {
    id: text('id').primaryKey(),
    courseId: text('course_id')
      .notNull()
      .references(() => courses.id, { onDelete: 'cascade' }),
    controlId: text('control_id')
      .notNull()
      .references(() => controls.id, { onDelete: 'cascade' }),
    orderIdx: integer('order_idx').notNull(),
  },
  (t) => [uniqueIndex('course_controls_order').on(t.courseId, t.orderIdx)]
);

// ---------------------------------------------------------------------------
// competitors — mutable. REQ-PRIV-001 (consent_at_ms), REQ-PRIV-002 (name +
// club are scrubbable in plan 17). C-M4 locks consent_status. D-11 partial
// unique index on (competition_id, card_number) where card_number IS NOT NULL.
// ---------------------------------------------------------------------------

export const competitors = sqliteTable(
  'competitors',
  {
    id: text('id').primaryKey(),
    competitionId: text('competition_id')
      .notNull()
      .references(() => competitions.id, { onDelete: 'cascade' }),
    /** Scrubbable PII per REQ-PRIV-002 (plan 17 nulls / anonymises). */
    name: text('name').notNull(),
    /** Scrubbable PII per REQ-PRIV-002 (plan 17 nulls / anonymises). */
    club: text('club'),
    classId: text('class_id')
      .notNull()
      .references(() => classes.id),
    /** NULL = no card pre-assigned; bound at walk-up or first read (D-11). */
    cardNumber: integer('card_number'),
    /** REQ-PRIV-001 — timestamp of recorded consent; NULL allowed when
     * consent_status='pending_first_read' (the operator has not yet
     * confirmed for this competitor). */
    consentAtMs: integer('consent_at_ms'),
    /** C-M4: 'explicit' (walk-up checkbox), 'pending_first_read'
     * (EntryList import), 'confirmed_on_read' (one-time toast confirmed). */
    consentStatus: text('consent_status', {
      enum: ['explicit', 'pending_first_read', 'confirmed_on_read'],
    })
      .notNull()
      .default('explicit'),
    /** REQ-PRIV-002 — set when PII columns nulled by plan 17 daily scrub;
     * non-null indicates an anonymized row. */
    scrubbedAtMs: integer('scrubbed_at_ms'),
  },
  (t) => [
    // D-11 partial unique index: same physical card cannot be bound to two
    // competitors within a single competition. NULL card_number is allowed
    // multiply (un-attached competitors).
    uniqueIndex('competitors_card_per_comp')
      .on(t.competitionId, t.cardNumber)
      .where(sql`${t.cardNumber} IS NOT NULL`),
  ]
);

// ---------------------------------------------------------------------------
// clubs — mutable autocomplete cache. UI-SPEC §"Walk-up modal" backs the
// club autocomplete with this table. name is the natural key (primary key
// directly); last_seen_at_ms is updated on every bind/walk-up so stale
// clubs naturally rank lower in the autocomplete sort.
// ---------------------------------------------------------------------------

export const clubs = sqliteTable('clubs', {
  name: text('name').primaryKey(),
  lastSeenAtMs: integer('last_seen_at_ms').notNull(),
});

// ---------------------------------------------------------------------------
// config — internal singleton key/value store. Plan 02 uses key='node_id'
// for the per-install node identifier (stable across restarts — REQ-OPS-002).
// No FKs; intentionally simple.
// ---------------------------------------------------------------------------

export const config = sqliteTable('config', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});

// ---------------------------------------------------------------------------
// events — immutable, append-only. PRIMARY KEY (node_id, local_seq) per
// research/architecture.md. competition_id is nullable (pre-competition
// events from the idle bridge). Append-only invariant enforced by the
// hand-authored 0001_append_only_triggers.sql migration (C-H1).
// ---------------------------------------------------------------------------

export const events = sqliteTable(
  'events',
  {
    nodeId: text('node_id').notNull(),
    localSeq: integer('local_seq').notNull(),
    /** NULL = pre-competition event (e.g. idle bridge connection_changed). */
    competitionId: text('competition_id').references(() => competitions.id),
    eventType: text('event_type').notNull(),
    /** Host clock at the event itself (ms epoch). */
    eventTimeMs: integer('event_time_ms').notNull(),
    /** Host clock at insert time (ms epoch). May differ for replayed events. */
    recordedAtMs: integer('recorded_at_ms').notNull(),
    payload: text('payload', { mode: 'json' }).notNull().$type<EventPayload>(),
  },
  (t) => [
    primaryKey({ columns: [t.nodeId, t.localSeq] }),
    index('idx_events_time').on(t.eventTimeMs),
    index('idx_events_comp').on(t.competitionId),
    index('idx_events_comp_type').on(t.competitionId, t.eventType),
  ]
);
